### ISSUE TITLE
Polymorphic tables cause ValueError: can't find value for column parent.name in the results returned

### ISSUE THREAD

**Issue by mekhami** [djrobstep/sqlakeyset#7]
I have a structure where I query my Child table which has a Parent table.
```
class Child(Parent):
    child_id = Column(Integer, ForeignKey(Parent.parent_id), primary_key=True)

    __mapper_args__ = {
        'polymorphic_identity': CLS_INDEX['Child'],  # comes from elsewhere in the code
        'inherit_condition': (child_id == Parent.parent_id)
    }
    ...

class Parent(Base):
    name = Column(String)
    parent_id = Column(Integer, primary_key=True)
    ...
```

When I try to query Child.name, I receive the ValueError in the title.

```
>>> q = session.query(Child).order_by(Child.name)
>>> get_page(q, per_page=50)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mekhami/.envs/lab7/local/lib/python2.7/site-packages/sqlakeyset/paging.py", line 250, in get_page
    backwards)
  File "/home/mekhami/.envs/lab7/local/lib/python2.7/site-packages/sqlakeyset/paging.py", line 143, in orm_get_page
    current_marker=place)
  File "/home/mekhami/.envs/lab7/local/lib/python2.7/site-packages/sqlakeyset/paging.py", line 39, in orm_page_from_rows
    paging = Paging(rows, page_size, ocols, backwards, current_marker, get_marker)
  File "/home/mekhami/.envs/lab7/local/lib/python2.7/site-packages/sqlakeyset/results.py", line 115, in __init__
    self.marker_1 = get_marker(rows[0], ocols)
  File "/home/mekhami/.envs/lab7/local/lib/python2.7/site-packages/sqlakeyset/paging.py", line 109, in orm_placemarker_from_row
    return tuple(get_value(x) for x in ocols)
  File "/home/mekhami/.envs/lab7/local/lib/python2.7/site-packages/sqlakeyset/paging.py", line 109, in <genexpr>
    return tuple(get_value(x) for x in ocols)
  File "/home/mekhami/.envs/lab7/local/lib/python2.7/site-packages/sqlakeyset/paging.py", line 108, in get_value
    raise ValueError(CANT_FIND.format(ocol.full_name))
ValueError: can't find value for column parent.name in the results returned
```

**Comment by chenghlee** [comment]
To clarify, this is the inheritance pattern that triggers the error:

``` python
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Parent(Base):
    id_ = Column(Integer, primary_key=True)
    cls = Column(Integer, nullable=False, default=0)
    name = Column(String)

    __tablename__ = 'parent'
    __mapper_args__ = {
        'polymorphic_on': cls,
        'polymorphic_identity': 0
    }


class ChildA(Parent):
    child_a_id = Column(Integer, ForeignKey('parent.id_'), primary_key=True)

    __tablename__ = 'child_a'
    __mapper_args__ = {'polymorphic_identity': 1}


class ChildB(Parent):
    child_b_id = Column(Integer, ForeignKey('parent.id_'), primary_key=True)

    __tablename__ = 'child_b'
    __mapper_args__ = {'polymorphic_identity': 2}
```

The problem seems to come from [paging.py, line 74](https://github.com/djrobstep/sqlakeyset/blob/master/sqlakeyset/paging.py#L74)
``` python
if entity.__tablename__ == ocol.table_name:
```
For the joined table inheritance pattern, `entity.__tablename__` is not equal to `ocol.table_name` if `ocol` comes from the parent table. If you replace that `if` with something like:
``` python
if hasattr(thing, ocol.name):
```
this bug disappears. But _strong warning_, I'm not 100% where using `hasattr` would break any or everything else in the package.

**Comment by djrobstep** [comment]
Hi, thank you to both of you for reporting this issue!

@chenghlee your suggested change and rationale seems reasonable and I'm happy to make this change (provided the existing tests still pass of course). Do either of you feel like putting together a pull request for this with a simple test case?

Or else I'll fix it up when I get around to it, however that may take a while as I am rather busy at the moment.

**Comment by chenghlee** [comment]
@djrobstep: I should have some time over the next few days to put together a pull request for this.

**Comment by djrobstep** [comment]
@chenghlee Super stuff! If you have any questions about the code or whatever just ask.
