### ISSUE TITLE
Breaks when using sqlalchemy session

### ISSUE THREAD

**Issue by ddorian** [djrobstep/sqlakeyset#97]
Breaks when using .session(), see:

```python
import sqlalchemy as sa
from sqlakeyset import select_page
from sqlalchemy import Integer
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column


class Base(DeclarativeBase):
    pass


from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg://postgres:1@127.0.0.1:5432/guru", echo=True)


class User2(Base):
    __tablename__ = "user2"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)


with Session(engine) as session:
    query_breaks = sa.select(User2).order_by(User2.id)
    page_breaks = select_page(session, query_breaks, per_page=3)
    print([type(page_breaks), page_breaks.paging.next])

    page_breaks = select_page(session, query_breaks, per_page=3, after=page_breaks.paging.next)

``````
Output:
```python
Traceback (most recent call last):
  File "/home/guru/Desktop/my_project/minimal.py", line 26, in <module>
    page_breaks = select_page(session, query_breaks, per_page=3, after=page_breaks.paging.next)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guru/Desktop/my_project/.venv/lib/python3.11/site-packages/sqlakeyset/paging.py", line 411, in select_page
    return core_get_page(session, selectable, per_page, place, backwards)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guru/Desktop/my_project/.venv/lib/python3.11/site-packages/sqlakeyset/paging.py", line 286, in core_get_page
    sel = prepare_paging(
          ^^^^^^^^^^^^^^^
  File "/home/guru/Desktop/my_project/.venv/lib/python3.11/site-packages/sqlakeyset/paging.py", line 214, in prepare_paging
    condition = where_condition_for_page(order_cols, place, dialect)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guru/Desktop/my_project/.venv/lib/python3.11/site-packages/sqlakeyset/paging.py", line 97, in where_condition_for_page
    raise InvalidPage(
sqlakeyset.serial.serial.InvalidPage: Page marker has different column count to query's order clause
```

**Comment by acarapetis** [comment]
I think the issue is that you're passing a *marker* (i.e. a pair `(keyset, direction)`) to the argument `after=` which expects only a keyset. Try `page=page_breaks.paging.next` instead of `after=page_breaks.paging.next`.

**Comment by ddorian** [comment]
You're correct. For some reason, I read the docs wrong. Sorry about that. Thank you!
